freeproxy_only: true
maxpages: 150
freeproxy_list:
  - US1:
      country: US
      speed: 2500
      type: https
  - US2:
      country: US
      speed: 2500
      type: socks4
  - USS:
      country: US
      speed: 2500
      type: socks5
  - DE1:
      country: DE
      speed: 2500
      type: https
  - DE2:
      country: DE
      speed: 2500
      type: socks4
  - DE3:
      country: DE
      speed: 2500
      type: socks5
  - GB1:
      country: GB
      speed: 2500
      type: https
  - GB2:
      country: GB
      speed: 2500
      type: socks4
  - GB3:
      country: GB
      speed: 2500
      type: socks5
  - FR1:
      country: FR
      speed: 2500
      type: https
  - FR2:
      country: FR
      speed: 2500
      type: socks4
  - FR3:
      country: FR
      speed: 2500
      type: socks5
  - CA1:
      country: CA
      speed: 2500
      type: https
  - CA2:
      country: CA
      speed: 2500
      type: socks4
  - CA3:
      country: CA
      speed: 2500
      type: socks5
  - NL1:
      country: NL
      speed: 2500
      type: https
  - NL2:
      country: NL
      speed: 2500
      type: socks4
  - NL3:
      country: NL
      speed: 2500
      type: socks5
  - CH1:
      country: CH
      speed: 2500
      type: https
  - CH2:
      country: CH
      speed: 2500
      type: socks4
  - CH3:
      country: CH
      speed: 2500
      type: socks5
  - SE1:
      country: SE
      speed: 2500
      type: https
  - SE2:
      country: SE
      speed: 2500
      type: socks4
  - SE3:
      country: SE
      speed: 2500
      type: socks5
  - BE1:
      country: BE
      speed: 2500
      type: https
  - BE2:
      country: BE
      speed: 2500
      type: socks4
  - BE3:
      country: BE
      speed: 2500
      type: socks5
  - NO1:
      country: NO
      speed: 2500
      type: https
  - NO2:
      country: NO
      speed: 2500
      type: socks4
  - NO3:
      country: NO
      speed: 2500
      type: socks5
  - AT1:
      country: AT
      speed: 2500
      type: https
  - AT2:
      country: AT
      speed: 2500
      type: socks4
  - AT3:
      country: AT
      speed: 2500
      type: socks5
  - DK1:
      country: DK
      speed: 2500
      type: https
  - DK2:
      country: DK
      speed: 2500
      type: socks4
  - DK3:
      country: DK
      speed: 2500
      type: socks5
  - IE1:
      country: IE
      speed: 2500
      type: https
  - IE2:
      country: IE
      speed: 2500
      type: socks4
  - IE3:
      country: IE
      speed: 2500
      type: socks5
  - FI1:
      country: FI
      speed: 2500
      type: https
  - FI2:
      country: FI
      speed: 2500
      type: socks4
  - FI3:
      country: FI
      speed: 2500
      type: socks5
  - LU1:
      country: LU
      speed: 2500
      type: https
  - LU2:
      country: LU
      speed: 2500
      type: socks4
  - LU3:
      country: LU
      speed: 2500
      type: socks5
  - IS1:
      country: IS
      speed: 2500
      type: https
  - IS2:
      country: IS
      speed: 2500
      type: socks4
  - IS3:
      country: IS
      speed: 2500
      type: socks5
  - MC1:
      country: MC
      speed: 2500
      type: https
  - MC2:
      country: MC
      speed: 2500
      type: socks4
  - MC3:
      country: MC
      speed: 2500
      type: socks5
  - LI1:
      country: LI
      speed: 2500
      type: https
  - LI2:
      country: LI
      speed: 2500
      type: socks4
  - LI3:
      country: LI
      speed: 2500
      type: socks5
  - MX1:
      country: MX
      speed: 2500
      type: https
  - MX2:
      country: MX
      speed: 2500
      type: socks4
  - MX3:
      country: MX
      speed: 2500
      type: socks5

# https://www.freeproxy.world/?type={.type}&anonymity={.anonymity}&country={.country}&speed={.speed}&port={.port}
