freeproxy_list:
  - US4:
      country: US
      speed: 2500
      type: socks4
  - US5:
      country: US
      speed: 2500
      type: socks5

# https://www.freeproxy.world/?type={.type}&anonymity={.anonymity}&country={.country}&speed={.speed}&port={.port}
