name: Auto Update

on:
  push:
  schedule:
    - cron: '0 */8 * * *'
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  scraper:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: actions-workflow-metrics
        uses: dev-hato/actions-workflow-metrics@v0.0.7

      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Setup uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Install dependencies
        run: |
          uv sync --no-dev
          chmod -R 777 .venv
          sudo apt-get install xvfb

      - name: Download Geolocation Databases
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api -H "Accept: application/vnd.github.raw" /repos/wp-statistics/GeoLite2-City/contents/GeoLite2-City.mmdb.gz > GeoLite2-City.mmdb.gz
          gzip -df GeoLite2-City.mmdb.gz
          gh api -H "Accept: application/vnd.github.raw" /repos/wp-statistics/DbIP-City-lite/contents/dbip-city-lite.mmdb.gz > dbip-city-lite.mmdb.gz
          gzip -df dbip-city-lite.mmdb.gz
          gh api -H "Accept: application/vnd.github.raw" /repos/lionsoul2014/ip2region/contents/data/ip2region_v4.xdb > ip2region_v4.xdb

      - name: Configure hosts
        run: |
          sudo tee -a /etc/hosts <<EOF
          0.0.0.0 fonts.googleapis.com
          0.0.0.0 fonts.gstatic.com
          0.0.0.0 pagead2.googlesyndication.com
          0.0.0.0 static.cloudflareinsights.com
          0.0.0.0 googletagmanager.com
          0.0.0.0 www.googletagmanager.com
          EOF

      - name: Run Scraper
        env:
          PYTHONUNBUFFERED: "1"
        run: uv run main.py

      - name: Commit Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update configs $(date '+%Y-%m-%d %H:%M:%S') [skip ci]"
            git push origin main
          fi
